
export const OLYMPIC_API_CALL_REQUEST = "OLYMPIC_API_CALL_REQUEST";
export const OLYMPIC_API_CALL_SUCCESS = "OLYMPIC_API_CALL_SUCCESS";
export const OLYMPIC_API_CALL_FAILURE = "OLYMPIC_API_CALL_FAILURE";

export const PIE_CHART = 'PIE_CHART';

export const LOAD_ALL_USERS = "LOAD_ALL_USERS";
export const FILTER_BY_VALUE = "FILTER_BY_VALUE";
export const FILTER_USERS = "FILTER_USERS";

export const SEARCH_OLYMPICS = "SEARCH_OLYMPICS";
export const CHART_OPTIONS = "CHART_OPTIONS";
export const SHOW_PANE = "SHOW_PANE";
export const SHOW_ROW_DETAILS = "SHOW_ROW_DETAILS";




